name: Destroy EasyBuggy For Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'    

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Destroy EasyBuggy
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACC_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_S_KEY }}
        aws-region: eu-west-1 
    - name: Check Terraform
      run: |
        which terraform
        terraform -version
    - name: Destroy machine
      working-directory: ./deploy/terraform
      run: |
        terraform init
        terraform workspace select demo
        terraform destroy --auto-approve        
